---
#Used to enable container VPN connection
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    privileged: true
    cap_add:
      - NET_ADMIN
#    Used to enable tun      
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080       # qbitorrent
      - 61951:61951     # qbitorrent
      - 61951:61951/udp # qbitorrent
    volumes:
      - ${ROOT_DIR}/docker/gluetun-config:/config
    environment:
      - PUID=13001
      - PGID=${PGID}
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY="Private Key"
      - WIREGUARD_ADDRESSES="IP Address"
      - SERVER_CITIES=Chicago IL
      - TZ=${TIMEZONE}
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=13002
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${ROOT_DIR}/docker/qbittorent-config:/config
      - torrents:/data/torrents
    restart: unless-stopped

volumes:
  torrents:
    driver_opts:
      type: "nfs"
      o: "addr="ip address",nolock,rw,soft,nfsvers=4"
      device: "location"